### ISSUE TITLE
New Gradle version compatibility

### ISSUE THREAD

**Issue by Soamid** [rzabini/gradle-jython#11]
I'm using Gradle 4.4.1 in my project and tried to configure this plugin. When I try to add Jython dependencies with pypackage, I get following error:

`java.lang.ClassNotFoundException: org.gradle.logging.ProgressLogger`

When I switch into older Gradle (2.12) everything works so I assume it's version compatibility issue.

**Comment by rzabini** [comment]
I am not able to replicate this issue, if I use the plugin in a project which uses Gradle 4.4.1 I just get a "deprecation warning", but the tasks execute just fine.
Can you provide a sample `build.gradle` which causes the error?

**Comment by Soamid** [comment]
Sure, though my original build.gradle is rather large and complex, I've managed to find a simpler example: 
```
group 'test'
version '1.0-SNAPSHOT'


apply plugin: 'java'

sourceCompatibility = 1.8

buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "gradle.plugin.com.github.rzabini:gradle-jython:1.0.4"
    }
}

apply plugin: "com.github.rzabini.gradle-jython"

jython {
    pypackage('beautifulsoup4:4.6.0') {
        module 'bs4'
    }

    pypackage 'tabulate:0.8.2'
}


def sayHello="""
print 'hello from $project.name'
"""

task testJython(type: jython.JythonTask) {
    script sayHello
}
```
Invoking `gradlew testJython` ends with an error with following stacktrace:
```
aused by: java.lang.NoClassDefFoundError: Lorg/gradle/logging/ProgressLogger;
        at org.gradle.internal.metaobject.BeanDynamicObject.getMetaClass(BeanDynamicObject.java:160)
        at org.gradle.internal.metaobject.BeanDynamicObject.access$400(BeanDynamicObject.java:55)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:218)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
        at org.gradle.internal.metaobject.ConfigureDelegate.getProperty(ConfigureDelegate.java:112)
        at jython.JythonExtension$_downloadJythonPackage_closure2.doCall(JythonExtension.groovy:67)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at de.undercouch.gradle.tasks.download.DownloadExtension.configure(DownloadExtension.java:42)
        at de.undercouch.gradle.tasks.download.DownloadExtension.configure(DownloadExtension.java:29)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:104)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:173)
        at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:70)
        at org.gradle.api.internal.plugins.DefaultConvention.configureExtension(DefaultConvention.java:367)
        at org.gradle.api.internal.plugins.DefaultConvention.access$500(DefaultConvention.java:45)
        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.tryInvokeMethod(DefaultConvention.java:310)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:160)
        at org.gradle.api.internal.project.DefaultProject_Decorated.invokeMethod(Unknown Source)
        at jython.JythonExtension.downloadJythonPackage(JythonExtension.groovy:66)
        at jython.JythonExtension$downloadJythonPackage$0.callCurrent(Unknown Source)
        at jython.JythonExtension.installPackage(JythonExtension.groovy:55)
        at jython.JythonExtension$installPackage.callCurrent(Unknown Source)
        at jython.JythonExtension.pypackage(JythonExtension.groovy:43)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:479)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryInvokeMethod(BeanDynamicObject.java:191)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:57)
        at build_7h97q5wezktki10bl4mi6ogy9$_run_closure1.doCall(S:\Uczelnia\TO2\2017\SDDS\build.gradle:23)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:71)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.util.ConfigureUtil$1.execute(ConfigureUtil.java:123)
        at org.gradle.api.internal.plugins.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:173)
        at org.gradle.api.internal.plugins.ExtensionsStorage.configureExtension(ExtensionsStorage.java:70)
        at org.gradle.api.internal.plugins.DefaultConvention.configureExtension(DefaultConvention.java:367)
        at org.gradle.api.internal.plugins.DefaultConvention.access$500(DefaultConvention.java:45)
        at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.tryInvokeMethod(DefaultConvention.java:310)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
        at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:134)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:160)
        at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:83)
        at build_7h97q5wezktki10bl4mi6ogy9.run(S:\Uczelnia\TO2\2017\SDDS\build.gradle:22)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 93 more
Caused by: java.lang.ClassNotFoundException: org.gradle.logging.ProgressLogger
        ... 142 more
```

When I change gradle version using `gradlew wrapper --gradle-version 2.12`, everything works fine. When Jython dependencies are downloaded, there is also no error on Gradle 4.4.1 (but after `gradlew clean` the problem returns).

**Comment by rzabini** [comment]
Thank you,
It is a compatibility problem in `gradle download task`, a plugin I use to download Python packages.
It seems a recurrent issue: https://github.com/michel-kraemer/gradle-download-task/issues?utf8=%E2%9C%93&q=ProgressLogger, anyway now it seems to be fixed on the last release of that plugin.
I will try to upgrade the dependency in my plugin, and see if problem gets solved.

**Comment by Soamid** [comment]
I downloaded your source code and bumped gradle-download-task to 3.3.0. Everything seems to be ok now! :)
