### ISSUE TITLE
DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.

### ISSUE THREAD

**Issue by pgunia** [rzabini/gradle-jython#3]
Since a couple of days I'm having issues using the Gradle plugin. Here's the task definition for my `jythonDependencies`:

```
task jythonDependencies {
    jython {
       pypackage 'requests:2.12.3'
       pypackage 'python-dateutil:2.5.3'
       pypackage 'six:1.10.0'
    }
}
```

Here's an excerpt from the stacktrace that I get when I try to run this gradle task. 

```
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 10; DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1239)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at jython.util.PackageFinder.findPackageArchive(PackageFinder.groovy:47)
        at jython.util.PackageFinder$findPackageArchive$0.callStatic(Unknown Source)
        at jython.util.PackageFinder.findPackageArchive(PackageFinder.groovy:54)
        at jython.util.PackageFinder$findPackageArchive.call(Unknown Source)
        at jython.JythonExtension.downloadJythonPackage(JythonExtension.groovy:53)
        at jython.JythonExtension$downloadJythonPackage.callCurrent(Unknown Source)
        at jython.JythonExtension.installPackage(JythonExtension.groovy:49)
        at jython.JythonExtension$_pypackage_closure1.doCall(JythonExtension.groovy:36)
```

I've taken a closer look at the code of the `jython.util.PackageFinder.findPackageArchive` method and I think, the problem could be solved by simply configuring the `XMLSlurper` using the following settings:

```
parser.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false); 
parser.setFeature("http://xml.org/sax/features/namespaces", false) 
```

I don't know exactly why this popped up recently, but maybe pypackage just added the DOCTYPE declaration to their HTML.

**Comment by rzabini** [comment]
You are right. I added the 'requests:2.12.3' package to the test, and verified the issue you mentioned. The test is now fixed as per your suggestion (the first directive was sufficient). If it works for you I will close the issue.
Thank you.

**Comment by pgunia** [comment]
Thanks for checking! I just tried to build the project and it fails with the following CodeNarc violations, that seem to be related to the lines you've added:

```
:codenarcMain FAILED

2 (0 / 0 / 2) CodeNarc violations were found in 1 files

[Convention | NoDef] jython.util.PackageFinder:47  (priority 3)
        >> def parser = new XmlSlurper()
  def should not be used
  def should not be used. You should replace it with concrete type.
  http://codenarc.sourceforge.net/codenarc-rules-convention.html#NoDef

[Unnecessary | UnnecessaryGString] jython.util.PackageFinder:48  (priority 3)
        >> parser.setFeature("http://apache.org/xml/features/disallow-doctype-decl", false)
  The String 'http://apache.org/xml/features/disallow-doctype-decl' can be wrapped in single quotes instead of double quotes
  String objects should be created with single quotes, and GString objects created with double quotes. Creating normal String objects with double quotes is confusing to readers.
  http://codenarc.sourceforge.net/codenarc-rules-unnecessary.html#UnnecessaryGString

FAILURE: Build failed with an exception.
```

**Comment by rzabini** [comment]
Yes, right, I wasn't aware that the automatic build on Travis had been deactivated, so I didn't know about the failing build (I just ran the tests in my IDE). Now I reactivated the build and, after the corrections suggested by CodeNarc, it seems fine.

**Comment by pgunia** [comment]
I've had some problems with incompatible Groovy versions due to the fact that I'm using Gradle 3.1, but that's more of a setup problem on my side. The fix itself works as expected. 

Thanks for fixing!

**Comment by rzabini** [comment]
Fixed
